version: "2.0"
services:
  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-1-prerelease-20201202
    volumes:
      - /dev/shm:/dev/shm
    # depends_on:
    #   - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"